name: Validate

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    name: HACS Integration
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        id: hacs
        with:
          category: "integration"

      - name: Post a message in a channel
        uses: slackapi/slack-github-action@v2.1.1
        if: failure()
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"

  validate-hassfest:
    runs-on: ubuntu-latest
    name: Hassfest checks
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
